import = ["/home/alls/.config/alacritty/everforest.toml",]

[font]
size = 8.5

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Medium"

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true

[colors]
cursor = {cursor = "0xd3c6aa", text = "0x232a2e"}
vi_mode_cursor = {cursor = "0xd3c6aa", text = "0x232a2e"}
