[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true

[colors]
cursor = {text = "0x282828", cursor = "0xebdbb2"}
vi_mode_cursor = {text = "0x282828", cursor = "0xebdbb2"}
